language: php

sudo: true

php:
  -7.1

sudo: false


cache:
  directories:
    - laravel #only cache the laravel directory

services: mysql

install:
  # create a new database for the hyn connection
  - export DB_USERNAME=travis DB_DATABASE=foro_tests DB_PASSWORD= QUEUE_DRIVER=sync
  #run the setup script
  - curl -s https://raw.githubusercontent.com/kevupton/docker-laravel-tests/master/setup.sh | bash

script:
  #script to setup the package for testing
  - cd laravel
  - composer update
  - php artisan vendor:publish --force
  - php artisan migrate --seed #setups the migrations and seeding
  - phpunit "vendor/phpunit/bin" #runs the phpunit just for your package.
